root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = ["--host", "localhost", "--public", "./dist"]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./main.go"
delay = 200
exclude_dir = ["assets", "tmp", "vendor", "node_modules", "public"]
# exclude_file = []
# exclude_regex = []
exclude_unchanged = false
follow_symlink = false
# full_bin = ""
include_dir = ["handlers", "models", "services", "utils", "pkg", "templates"]
include_ext = ["go", "tmpl"]
include_file = ["main.go", "dist/assets/style-*.css"]
kill_delay = 5000000000 # nanosecond
log = "build-errors.log"
poll = false
poll_interval = 0
# Workaround for shutting down the server (https://github.com/cosmtrek/air/issues/534)
post_cmd = ["lsof -i tcp:8080 | awk 'NR==2{print $2}' | xargs kill"]
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
