name: Build and deploy

on:
  push:
    branches: ["migration-to-golang"]
jobs:
  build-mcmamina:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.5"

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm install && pnpm build

      - name: Install go dependencies
        run: go mod download && go install github.com/a-h/templ/cmd/templ@latest

      - name: Build BE
        run: templ generate && go build -o mcmamina ./main.go
