name: Build and deploy

on:
  push:
    branches: ["migration-to-golang"]
jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build FE
        run: pnpm build

      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.5"

      - name: Install go dependencies
        run: go mod download

      - name: Build BE
        run: go build -o mcmamina ./main.go
